# Generated by Django 5.1 on 2024-08-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='updated_at',
            new_name='updated_on',
        ),
    ]
