# Generated by Django 5.1 on 2024-08-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_rename_created_at_profile_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
