# Generated by Django 5.1 on 2024-08-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_rename_created_at_story_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='instagram_clone/media/DSC_1022.JPG', null=True, upload_to=''),
        ),
    ]
